#############################################################################
# Makefile for building: QDmxLib
# Generated by qmake (3.1) (Qt 5.9.2)
# Project:  QDmxLib.pro
# Template: subdirs
# Command: E:/Prog/Qt/5.9.2/mingw53_32/bin/qmake.exe -o Makefile QDmxLib.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = E:/Prog/Qt/5.9.2/mingw53_32/bin/qmake.exe
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = cp -f
INSTALL_PROGRAM = cp -f
INSTALL_DIR   = cp -f -R
QINSTALL      = E:/Prog/Qt/5.9.2/mingw53_32/bin/qmake.exe -install qinstall
QINSTALL_PROGRAM = E:/Prog/Qt/5.9.2/mingw53_32/bin/qmake.exe -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		sub-artnet \
		sub-e131 \
		sub-espnet \
		sub-dmxusb


sub-artnet-qmake_all:  FORCE
	@test -d artnet/ || mkdir -p artnet/
	cd artnet/ && $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/artnet/artnet.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug
	cd artnet/ && $(MAKE) -f Makefile qmake_all
sub-artnet: FORCE
	@test -d artnet/ || mkdir -p artnet/
	cd artnet/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/artnet/artnet.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile
sub-artnet-make_first: FORCE
	@test -d artnet/ || mkdir -p artnet/
	cd artnet/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/artnet/artnet.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile 
sub-artnet-all: FORCE
	@test -d artnet/ || mkdir -p artnet/
	cd artnet/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/artnet/artnet.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile all
sub-artnet-clean: FORCE
	@test -d artnet/ || mkdir -p artnet/
	cd artnet/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/artnet/artnet.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile clean
sub-artnet-distclean: FORCE
	@test -d artnet/ || mkdir -p artnet/
	cd artnet/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/artnet/artnet.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile distclean
sub-artnet-install_subtargets: FORCE
	@test -d artnet/ || mkdir -p artnet/
	cd artnet/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/artnet/artnet.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile install
sub-artnet-uninstall_subtargets: FORCE
	@test -d artnet/ || mkdir -p artnet/
	cd artnet/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/artnet/artnet.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile uninstall
sub-e131-qmake_all:  FORCE
	@test -d e131/ || mkdir -p e131/
	cd e131/ && $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/e131/e131.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug
	cd e131/ && $(MAKE) -f Makefile qmake_all
sub-e131: FORCE
	@test -d e131/ || mkdir -p e131/
	cd e131/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/e131/e131.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile
sub-e131-make_first: FORCE
	@test -d e131/ || mkdir -p e131/
	cd e131/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/e131/e131.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile 
sub-e131-all: FORCE
	@test -d e131/ || mkdir -p e131/
	cd e131/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/e131/e131.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile all
sub-e131-clean: FORCE
	@test -d e131/ || mkdir -p e131/
	cd e131/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/e131/e131.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile clean
sub-e131-distclean: FORCE
	@test -d e131/ || mkdir -p e131/
	cd e131/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/e131/e131.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile distclean
sub-e131-install_subtargets: FORCE
	@test -d e131/ || mkdir -p e131/
	cd e131/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/e131/e131.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile install
sub-e131-uninstall_subtargets: FORCE
	@test -d e131/ || mkdir -p e131/
	cd e131/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/e131/e131.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile uninstall
sub-espnet-qmake_all:  FORCE
	@test -d espnet/ || mkdir -p espnet/
	cd espnet/ && $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/espnet/espnet.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug
	cd espnet/ && $(MAKE) -f Makefile qmake_all
sub-espnet: FORCE
	@test -d espnet/ || mkdir -p espnet/
	cd espnet/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/espnet/espnet.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile
sub-espnet-make_first: FORCE
	@test -d espnet/ || mkdir -p espnet/
	cd espnet/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/espnet/espnet.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile 
sub-espnet-all: FORCE
	@test -d espnet/ || mkdir -p espnet/
	cd espnet/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/espnet/espnet.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile all
sub-espnet-clean: FORCE
	@test -d espnet/ || mkdir -p espnet/
	cd espnet/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/espnet/espnet.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile clean
sub-espnet-distclean: FORCE
	@test -d espnet/ || mkdir -p espnet/
	cd espnet/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/espnet/espnet.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile distclean
sub-espnet-install_subtargets: FORCE
	@test -d espnet/ || mkdir -p espnet/
	cd espnet/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/espnet/espnet.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile install
sub-espnet-uninstall_subtargets: FORCE
	@test -d espnet/ || mkdir -p espnet/
	cd espnet/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/espnet/espnet.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile uninstall
sub-dmxusb-qmake_all:  FORCE
	@test -d dmxusb/ || mkdir -p dmxusb/
	cd dmxusb/ && $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/dmxusb/dmxusb.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug
	cd dmxusb/ && $(MAKE) -f Makefile qmake_all
sub-dmxusb: FORCE
	@test -d dmxusb/ || mkdir -p dmxusb/
	cd dmxusb/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/dmxusb/dmxusb.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile
sub-dmxusb-make_first: FORCE
	@test -d dmxusb/ || mkdir -p dmxusb/
	cd dmxusb/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/dmxusb/dmxusb.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile 
sub-dmxusb-all: FORCE
	@test -d dmxusb/ || mkdir -p dmxusb/
	cd dmxusb/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/dmxusb/dmxusb.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile all
sub-dmxusb-clean: FORCE
	@test -d dmxusb/ || mkdir -p dmxusb/
	cd dmxusb/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/dmxusb/dmxusb.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile clean
sub-dmxusb-distclean: FORCE
	@test -d dmxusb/ || mkdir -p dmxusb/
	cd dmxusb/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/dmxusb/dmxusb.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile distclean
sub-dmxusb-install_subtargets: FORCE
	@test -d dmxusb/ || mkdir -p dmxusb/
	cd dmxusb/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/dmxusb/dmxusb.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile install
sub-dmxusb-uninstall_subtargets: FORCE
	@test -d dmxusb/ || mkdir -p dmxusb/
	cd dmxusb/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/dmxusb/dmxusb.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile uninstall

Makefile: QDmxLib.pro E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/win32-g++/qmake.conf E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/spec_pre.prf \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/qdevice.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/device_config.prf \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/common/g++-base.conf \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/common/angle.conf \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/common/sanitize.conf \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/common/gcc-base.conf \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/qconfig.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3danimation.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3danimation_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3dcore.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3dcore_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3dextras.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3dextras_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3dinput.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3dinput_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3dlogic.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3dlogic_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3dquick.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3dquick_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3dquickanimation.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3dquickextras.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3dquickinput.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3dquickrender.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3drender.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3drender_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_axbase.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_axbase_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_axcontainer.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_axcontainer_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_axserver.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_axserver_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_bluetooth.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_bluetooth_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_concurrent.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_concurrent_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_core.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_core_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_datavisualization.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_datavisualization_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_dbus.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_dbus_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_designer.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_designer_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_designercomponents_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_egl_support_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_fb_support_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_gamepad.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_gamepad_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_gui.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_gui_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_help.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_help_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_location.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_location_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_multimedia.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_network.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_network_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_networkauth.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_networkauth_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_nfc.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_nfc_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_opengl.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_opengl_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_openglextensions.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_positioning.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_positioning_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_printsupport.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_purchasing.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_purchasing_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_qml.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_qml_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_qmldebug_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_qmltest.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_quick.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_quick_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_quickwidgets.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_remoteobjects.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_repparser.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_repparser_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_script.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_script_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_scripttools.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_scripttools_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_scxml.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_scxml_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_sensors.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_sensors_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_serialbus.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_serialbus_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_serialport.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_serialport_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_sql.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_sql_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_svg.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_svg_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_testlib.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_testlib_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_texttospeech.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_texttospeech_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_theme_support_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_uiplugin.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_uitools.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_uitools_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_webchannel.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_webchannel_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_websockets.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_websockets_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_widgets.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_widgets_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_winextras.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_winextras_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_xml.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_xml_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/qt_functions.prf \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/qt_config.prf \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/win32-g++/qmake.conf \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/spec_post.prf \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/exclusive_builds.prf \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/toolchain.prf \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/default_pre.prf \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/win32/default_pre.prf \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/resolve_config.prf \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/exclusive_builds_post.prf \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/default_post.prf \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/qml_debug.prf \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/precompile_header.prf \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/warn_on.prf \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/qmake_use.prf \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/file_copies.prf \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/win32/windows.prf \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/testcase_targets.prf \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/exceptions.prf \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/yacc.prf \
		E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/lex.prf \
		QDmxLib.pro
	$(QMAKE) -o Makefile QDmxLib.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/spec_pre.prf:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/qdevice.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/device_config.prf:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/common/g++-base.conf:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/common/angle.conf:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/common/sanitize.conf:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/common/gcc-base.conf:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/qconfig.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3danimation.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3danimation_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3dcore.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3dcore_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3dextras.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3dextras_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3dinput.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3dinput_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3dlogic.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3dlogic_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3dquick.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3dquick_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3dquickanimation.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3dquickextras.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3dquickextras_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3dquickinput.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3dquickinput_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3dquickrender.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3dquickrender_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3dquickscene2d.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3drender.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_3drender_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_accessibility_support_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_axbase.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_axbase_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_axcontainer.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_axcontainer_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_axserver.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_axserver_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_bluetooth.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_bluetooth_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_bootstrap_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_concurrent.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_concurrent_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_core.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_core_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_datavisualization.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_datavisualization_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_dbus.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_dbus_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_designer.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_designer_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_designercomponents_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_egl_support_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_fb_support_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_gamepad.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_gamepad_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_gui.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_gui_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_help.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_help_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_location.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_location_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_multimedia.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_multimedia_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_network.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_network_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_networkauth.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_networkauth_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_nfc.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_nfc_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_opengl.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_opengl_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_openglextensions.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_openglextensions_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_packetprotocol_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_positioning.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_positioning_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_printsupport.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_printsupport_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_purchasing.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_purchasing_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_qml.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_qml_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_qmldebug_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_qmldevtools_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_qmltest.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_qmltest_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_quick.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_quick_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_quickparticles_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_quickwidgets.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_quickwidgets_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_remoteobjects.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_remoteobjects_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_repparser.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_repparser_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_script.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_script_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_scripttools.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_scripttools_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_scxml.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_scxml_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_sensors.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_sensors_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_serialbus.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_serialbus_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_serialport.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_serialport_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_sql.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_sql_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_svg.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_svg_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_testlib.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_testlib_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_texttospeech.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_texttospeech_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_theme_support_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_uiplugin.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_uitools.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_uitools_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_webchannel.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_webchannel_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_websockets.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_websockets_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_widgets.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_widgets_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_winextras.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_winextras_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_xml.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_xml_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/qt_functions.prf:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/qt_config.prf:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/win32-g++/qmake.conf:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/spec_post.prf:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/exclusive_builds.prf:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/toolchain.prf:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/default_pre.prf:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/win32/default_pre.prf:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/resolve_config.prf:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/exclusive_builds_post.prf:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/default_post.prf:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/qml_debug.prf:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/precompile_header.prf:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/warn_on.prf:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/qmake_use.prf:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/file_copies.prf:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/win32/windows.prf:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/testcase_targets.prf:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/exceptions.prf:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/yacc.prf:
E:/Prog/Qt/5.9.2/mingw53_32/mkspecs/features/lex.prf:
QDmxLib.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile QDmxLib.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: sub-artnet-qmake_all sub-e131-qmake_all sub-espnet-qmake_all sub-dmxusb-qmake_all FORCE

make_first: sub-artnet-make_first sub-e131-make_first sub-espnet-make_first sub-dmxusb-make_first  FORCE
all: sub-artnet-all sub-e131-all sub-espnet-all sub-dmxusb-all  FORCE
clean: sub-artnet-clean sub-e131-clean sub-espnet-clean sub-dmxusb-clean  FORCE
distclean: sub-artnet-distclean sub-e131-distclean sub-espnet-distclean sub-dmxusb-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-artnet-install_subtargets sub-e131-install_subtargets sub-espnet-install_subtargets sub-dmxusb-install_subtargets FORCE
uninstall_subtargets: sub-artnet-uninstall_subtargets sub-e131-uninstall_subtargets sub-espnet-uninstall_subtargets sub-dmxusb-uninstall_subtargets FORCE

sub-artnet-debug:
	@test -d artnet/ || mkdir -p artnet/
	cd artnet/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/artnet/artnet.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile debug
sub-e131-debug:
	@test -d e131/ || mkdir -p e131/
	cd e131/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/e131/e131.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile debug
sub-espnet-debug:
	@test -d espnet/ || mkdir -p espnet/
	cd espnet/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/espnet/espnet.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile debug
sub-dmxusb-debug:
	@test -d dmxusb/ || mkdir -p dmxusb/
	cd dmxusb/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/dmxusb/dmxusb.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile debug
debug: sub-artnet-debug sub-e131-debug sub-espnet-debug sub-dmxusb-debug

sub-artnet-release:
	@test -d artnet/ || mkdir -p artnet/
	cd artnet/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/artnet/artnet.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile release
sub-e131-release:
	@test -d e131/ || mkdir -p e131/
	cd e131/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/e131/e131.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile release
sub-espnet-release:
	@test -d espnet/ || mkdir -p espnet/
	cd espnet/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/espnet/espnet.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile release
sub-dmxusb-release:
	@test -d dmxusb/ || mkdir -p dmxusb/
	cd dmxusb/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/dmxusb/dmxusb.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile release
release: sub-artnet-release sub-e131-release sub-espnet-release sub-dmxusb-release

sub-artnet-check:
	@test -d artnet/ || mkdir -p artnet/
	cd artnet/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/artnet/artnet.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile check
sub-e131-check:
	@test -d e131/ || mkdir -p e131/
	cd e131/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/e131/e131.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile check
sub-espnet-check:
	@test -d espnet/ || mkdir -p espnet/
	cd espnet/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/espnet/espnet.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile check
sub-dmxusb-check:
	@test -d dmxusb/ || mkdir -p dmxusb/
	cd dmxusb/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/dmxusb/dmxusb.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile check
check: sub-artnet-check sub-e131-check sub-espnet-check sub-dmxusb-check

sub-artnet-benchmark:
	@test -d artnet/ || mkdir -p artnet/
	cd artnet/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/artnet/artnet.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile benchmark
sub-e131-benchmark:
	@test -d e131/ || mkdir -p e131/
	cd e131/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/e131/e131.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile benchmark
sub-espnet-benchmark:
	@test -d espnet/ || mkdir -p espnet/
	cd espnet/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/espnet/espnet.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile benchmark
sub-dmxusb-benchmark:
	@test -d dmxusb/ || mkdir -p dmxusb/
	cd dmxusb/ && ( test -e Makefile || $(QMAKE) -o Makefile D:/Programmation/Qt/QDmxLib/dmxusb/dmxusb.pro -spec win32-g++ CONFIG+=debug CONFIG+=qml_debug ) && $(MAKE) -f Makefile benchmark
benchmark: sub-artnet-benchmark sub-e131-benchmark sub-espnet-benchmark sub-dmxusb-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

